.gitignore
build.gradle
src/main/java/com/education/qporter/SwaggerController.java
src/main/resources/application.properties

- Swagger UI 세팅 & 테스트를 위한 내용 추가 정상 동작 리뷰 후 삭제 필요
- Actuator Health 세팅
https://naver.github.io/hackday-conventions-java/#_intellij

chore:SwaagerUI 세팅, Actuator:HealthCheck 세팅

---

src/main/java/com/education/qporter/WebConfig.java

-임시로 전역 CORS 설정을 해주기 위해 WebConfig 파일 생성

feat#3 : 임시로 전역 CORS 설정

---

build.gradle
githooks-src/commit-msg

EDU-77 refactor: gitHook 소스 수정

---

build.gradle
src/main/java/com/education/takeit/global/config/SecurityConfig.java
src/main/java/com/education/takeit/global/exception/CustomException.java
src/main/java/com/education/takeit/global/exception/ErrorResponseEntity.java
src/main/java/com/education/takeit/global/exception/GlobalExceptionHandler.java
src/main/java/com/education/takeit/global/exception/StatusCode.java
src/main/java/com/education/takeit/global/security/JwtUtils.java
src/main/java/com/education/takeit/user/dto/ReqSigninDto.java
src/main/java/com/education/takeit/user/dto/ReqSignupDto.java
src/main/java/com/education/takeit/user/entity/LoginType.java
src/main/java/com/education/takeit/user/entity/User.java
src/main/java/com/education/takeit/user/repository/UserRepository.java
src/main/java/com/education/takeit/user/service/UserService.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java
src/main/resources/application.yml

- 로그인/회원가입에 필요한 임시 초기 설정
- 임시로 사용할 h2 데이터 베이스 연결
- 임시로 jwt 토큰 발급해주는 JwtUtils 파일 생성
- 임시 User 엔티티 생성
-

EDU-14 feat : 자체 로그인/회원가입을 위한 jwt등의 초기 설정

---

src/main/java/com/education/takeit/global/dto/Message.java
src/main/java/com/education/takeit/global/security/JwtUtils.java
src/main/java/com/education/takeit/user/controller/UserController.java
src/main/java/com/education/takeit/user/service/UserService.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java

- 자체 회원가입 및 로그인 api 구현
- controller, Message dto 파일 생성
- controller 반환 형식을 통일하고 예외처리를 위해 Messge dto, StatusCode 파일을 생성했습니다.
- 예외처리에 필요한 정보는 StatusCode에 추가하고, data 반환이 필요할 경우 Messge dto를 참고해주시기 바랍니다.

EDU-14 feat: 자체 회원가입 및 로그인 기능 구현

---

src/main/java/com/education/takeit/global/config/SecurityConfig.java
src/main/java/com/education/takeit/global/exception/StatusCode.java
src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
src/main/java/com/education/takeit/user/dto/ReqSigninDto.java
src/main/java/com/education/takeit/user/dto/ReqSignupDto.java
src/main/java/com/education/takeit/user/entity/User.java
src/main/java/com/education/takeit/user/repository/UserRepository.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java

- 소셜 로그인에서 userId를 가져올 수 없기 때문에 입력받는 userId를 email로 변경
- 로그인과 스웨거 관련 요청은 필터를 거치치 않도록 설계
-

EDU-81 refactor: 로그인시 입력받는 userId를 email로 변경

---

build.gradle
src/main/java/com/education/takeit/global/config/SecurityConfig.java
src/main/java/com/education/takeit/global/config/SwaggerConfig.java
src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
src/main/resources/application.yml

- Swagger 초기설정에 필요한 파일 및 의존성 설정
- SwaggerConfig 추가
- SwaggerConfig 버전 업
-

EDU-14 feat: Swagger 초기설정에 필요한 파일 및 의존성 설정

---

githooks-src/commit-msg

- commit-msg 스크립트 수정
- commit-msg 스크립트 수정
- 브랜치에 프로젝트 넘버가 없을 경우 검증 패스

EDU-82 refactor: commit-msg-edit

---

src/main/java/com/education/takeit/global/config/SecurityConfig.java
src/main/java/com/education/takeit/user/entity/User.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java

refactor: userId 타입 Long으로 수정

---

.gitignore
build.gradle
src/main/java/com/education/takeit/global/config/SecurityConfig.java
src/main/java/com/education/takeit/global/config/SwaggerConfig.java
src/main/java/com/education/takeit/global/security/CustomUserDetails.java
src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
src/main/java/com/education/takeit/global/security/JwtUtils.java
src/main/java/com/education/takeit/global/security/service/CustomUserDetailService.java
src/main/java/com/education/takeit/user/controller/UserController.java
src/main/java/com/education/takeit/user/repository/UserRepository.java
src/main/java/com/education/takeit/user/service/UserService.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java
src/main/resources/application.yml
src/test/java/com/education/takeit/user/UserServiceTest.java

- 자체 회원가입을 한 사람 중 이메일이 중복되는지 확인하는 기능 추가
- 리프레시 토큰을 저장하기 위해 Redis 도입
- CustomUserDetail을 통해 인증 객체 등록하는 로직 추가
- Swagger에서 JWT를 인증할 수 있도록 SwaggerConfig코드 수정(헤더에서 엑세스 토큰을 확인)
- 주석 참고해주십쇼.

EDU-14 feat: 이메일 중복확인, 로그아웃 기능추가

---

src/main/java/com/education/takeit/global/config/SecurityConfig.java

- SecyrityConfig에 네이버 리다이렉트 경로 수정

refactor: securityConfig 경로 수정

---

src/main/java/com/education/takeit/global/config/SecurityConfig.java
src/main/java/com/education/takeit/global/exception/StatusCode.java
src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
src/main/java/com/education/takeit/global/security/JwtUserDetails.java
src/main/java/com/education/takeit/global/security/JwtUtils.java
src/main/java/com/education/takeit/user/controller/UserController.java
src/main/java/com/education/takeit/user/entity/User.java
src/main/java/com/education/takeit/user/repository/UserRepository.java
src/main/java/com/education/takeit/user/service/UserService.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java

- 디벨롭 브랜치에 머지하는 과정에서 발생한 충돌 해결
- 메소드 이름, config 코드에서 발생한 충돌 해결
-

EDU-16 chore: 회원 탈퇴 기능 충돌 해결

---

src/main/java/com/education/takeit/global/config/WebConfig.java

EDU 12 refactor: 인증 정보 포함으로 변경

---

src/main/java/com/education/takeit/user/controller/UserController.java
src/main/java/com/education/takeit/user/service/UserService.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java

- 네이버 로그인시 헤더에 토큰에 담기도록 수정
- 네이버 로그인 과정에서도 헤더에 토큰이 담기도록 수정
-

EDU-230 fix: 네이버 로그인시 토큰이 헤더에 담기도록 수정

---

src/main/java/com/education/takeit/TakeitApplication.java
src/main/java/com/education/takeit/oauth/client/NaverOauthClient.java
src/main/java/com/education/takeit/oauth/controller/OAuthController.java
src/main/java/com/education/takeit/oauth/service/NaverOAuthService.java
src/main/resources/application.yml

- 네이버 로그인 GET으로 변경 
- yml 파일 변수명 수정

EDU 12 fix: 네이버 로그인 GET 요청으로 변경

---

src/main/java/com/education/takeit/TakeitApplication.java
src/main/java/com/education/takeit/oauth/client/NaverOauthClient.java
src/main/java/com/education/takeit/oauth/controller/OAuthController.java
src/main/java/com/education/takeit/oauth/service/NaverOAuthService.java
src/main/resources/application.yml

Reverts LGCNS-PJT-EDU/EDU_BE#31

Revert "EDU 12 fix: 네이버 로그인 GET 요청으로 변경"

---

src/main/java/com/education/takeit/oauth/client/NaverOauthClient.java
src/main/java/com/education/takeit/oauth/controller/OAuthController.java
src/main/java/com/education/takeit/oauth/property/NaverProperties.java
src/main/java/com/education/takeit/oauth/service/NaverOAuthService.java
src/main/resources/application.yml

EDU 12 fix: 네이버 로그인 설정 파일 수정

---

build.gradle
src/main/java/com/education/takeit/global/config/GoogleOAuthConfig.java

- 중복 의존성 삭제
- Vulnerability found 해결
- 중복 의존성 삭제
- Vulnerability found 해결

EDU-13 chore: 중복 의존성 삭제, Vulnerability found 해결

---

src/main/java/com/education/takeit/oauth/client/GoogleOauthClient.java
src/main/java/com/education/takeit/oauth/dto/OAuthLoginRequest.java
src/main/java/com/education/takeit/oauth/dto/OAuthTokenResponse.java
src/main/java/com/education/takeit/oauth/dto/OIDCPublicKey.java
src/main/java/com/education/takeit/oauth/dto/OIDCPublicKeysResponse.java
src/main/java/com/education/takeit/oauth/service/GoogleOAuthService.java
src/main/java/com/education/takeit/oauth/service/KakaoOAuthService.java
src/main/java/com/education/takeit/oauth/service/NaverOAuthService.java
src/main/java/com/education/takeit/oauth/service/OidcPublicKeyService.java
src/test/java/com/education/takeit/oauth/service/GoogleOAuthServiceTest.java
src/test/java/com/education/takeit/oauth/service/KakaoOAuthServiceTest.java

- 소셜 로그인 (Google, Kakao) 테스트 코드 작성
- 소셜 로그인 (Google, Kakao) 테스트 코드 작성

Edu 13 be 카카오 로그인 로그아웃

---

src/main/java/com/education/takeit/user/entity/User.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java
src/test/java/com/education/takeit/user/UserServiceTest.java

- Users 테이블에 email unique 조건 삭제 및 자체 회원가입 테스트 코드 수정
- Users 테이블에 email unique 조건 삭제
- 회원가입 예외처리에서 loginType을 비교안하던 로직 수정
- 회원가입 테스트 코드 수정
-

EDU-232 fix: 회원 가입 예외처리 수정 및 테스트 코드 수정

---

src/main/java/com/education/takeit/global/config/WebConfig.java

EDU-244 fix: 헤더 접근 가능하도록 수정

---

src/test/java/com/education/takeit/user/UserServiceTest.java

- 회원 탈퇴 시나리오에 따른 테스트 추가
- 회원 탈퇴 테스트를 추가
- 활성화된 계정에 대한 회원 탈퇴 시도
- 존재하지 않는 유저에 대한 회원 탈퇴 시도
-

EDU-16 test: 회원탈퇴 테스트 추가

---

.github/workflows/integration.yml
src/main/java/com/education/takeit/global/security/JwtUtils.java

- workflow에 코드 최신화 과정 추가
- 코드 스타일 수정 후 반영하는 push 과정에서 코드가 최신화가 안돼서 푸쉬가 안되는 오류를 해결하기위해 rebase 과정 추가

chore: GithubActions workflow 수정

---

.github/workflows/integration.yml
build.gradle

- 테스트 코드에 필요한 h2 의존성 추가
- h2 의존성 추가
-

chore: 테스트 코드에 필요한 h2 의존성 추가

---

src/main/java/com/education/takeit/global/security/JwtUtils.java

EDU-246 refactor: 토큰 유효시간 원복

---

src/main/java/com/education/takeit/user/entity/User.java
src/test/java/com/education/takeit/oauth/service/NaverOAuthServiceTest.java

- 네이버 로그인 테스트 코드 수정
- 테스트 시나리오 상으로 login 메소드를 실행하기 전에 mock 객체가 동작을 준비하도록 코드 순서 변경
-

EDU-246 test: 네이버 로그인 테스트 코드 수정

---

src/main/java/com/education/takeit/global/security/JwtUtils.java

- Redis에 리프레시 토큰 저장 및 삭제 시 키값 통일

EDU-246 chore: redis key rename

---

src/test/java/com/education/takeit/oauth/service/NaverOAuthServiceTest.java

EDU-238 refactor: 네이버 로그인 실패 테스트 케이스 추가

---

src/main/java/com/education/takeit/user/controller/UserController.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java

- 회원 탈퇴 시 redis에서 리프레시 토큰 삭제 
- 로그아웃 시 토큰 전달 방식 @RequestParam -> @RequestHeader로 수정 

Edu 259 be 회원 탈퇴 시 리프레시 토큰 삭제 추가 및 로그아웃 토큰 전달 방식 수정 

---

src/main/java/com/education/takeit/user/controller/UserController.java
src/main/java/com/education/takeit/user/service/UserService.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java
src/test/java/com/education/takeit/user/UserServiceTest.java

- 회원 탈퇴 테스트 코드 수정
- 회원 탈퇴 테스트 코드 흐름에서 리프레시 토큰이 삭제될 수 있도록 RedisTemplate Mock 데이터 생성
-

Edu 262 fix: 회원탈퇴 테스트 코드 수정

---

src/main/java/com/education/takeit/global/config/SecurityConfig.java

- SpringSecurity안에 CORS 설정 추가
- Spring MVC 단계에서만 해주었던 CORS 설정을 SpringSecurity에도 추가
-

Fix cors preflight error

---

src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
src/main/java/com/education/takeit/roadmap/repository/RoadmapManagementRepository.java
src/main/java/com/education/takeit/roadmap/service/RoadmapService.java

Edu 249 be 로드맵 기능 구현

---

src/main/java/com/education/takeit/exam/controller/PreExamController.java
src/main/java/com/education/takeit/exam/dto/ExamResponse.java
src/main/java/com/education/takeit/exam/service/PreExamService.java

Edu 106 be 사전 평가 문제 가져오기

---

src/test/java/com/education/takeit/diagnosis/service/DiagnosisServiceTest.java

Edu 89 개발 be 진단 서비스

---

.github/workflows/codeStyleCheck.yml
Dockerfile

- ecr에 이미지 업로드 되도록 워크플로우 수정
- 코드스타일 체크하는 워크플로우와 ecr에 이미지를 업로드하는 워크플로우 분리
-

EDU-275 feat: ecr에 이미지 업로드 되도록 워크플로우 수정

---

src/main/java/com/education/takeit/roadmap/entity/RoadmapManagement.java
src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
src/main/resources/db/20250501.sql

- 게스트 공통 진단 응답 Redis에 저장
- 회원 공통 진단 응답 DB에 저장 
- 게스트가 회원가입 했을 경우 공통 문제 응답, 과목 번호 가져와서 DB에 저장 

EDU-274 feat: 진단 공통 문제 응답 DB에 저장 및 게스트 응답 redis에 저장

---

src/main/java/com/education/qporter/global/config/WebConfig.java
src/main/java/com/education/takeit/exam/controller/PreExamController.java
src/main/java/com/education/takeit/exam/dto/ExamResponse.java
src/main/java/com/education/takeit/exam/service/PreExamService.java

- codestyle 맞추기
- main에 머지하는 단계에서 왜인지 모르겠지만 code style 통일이 안돼있어서 수동으로 해주는중입니다
-

chore: codestyle 맞추기

---

src/main/java/com/education/takeit/diagnosis/controller/DiagnosisController.java
src/main/java/com/education/takeit/diagnosis/service/DiagnosisService.java
src/main/java/com/education/takeit/global/dto/StatusCode.java
src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
src/main/java/com/education/takeit/roadmap/dto/RoadmapRequestDto.java
src/main/java/com/education/takeit/roadmap/dto/RoadmapResponseDto.java
src/main/java/com/education/takeit/roadmap/dto/RoadmapSaveResDto.java
src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
src/test/java/com/education/takeit/diagnosis/service/DiagnosisServiceTest.java

- 코드 컨벤션 맞춰서 코드 리팩토링
- 코드 컨벤션 맞춰서 코드 수정하고, RequestHeader에서 userId 추출하는 방법 수정했습니다.
-

Edu 279 be 코드 컨벤션 맞춰서 수정

---

src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
src/main/java/com/education/takeit/roadmap/dto/RoadmapFindResDto.java
src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
src/main/resources/db/20250501.sql

- 사용자 로드맵 제공 기능 구현
- 사용자 개인의 로드맵을 제공하는 기능 구현
-

Edu 280 be 사용자 로드맵 제공 기능 구현

---

src/main/resources/application-dev.yml
src/test/java/com/education/takeit/roadmap/service/RoadmapCreateTest.java

- 로드맵 테스트 코드 작성
- 로드맵 생성에 대한 테스트 코드 작성
-

EDU-281 test: 로드맵 생성 테스트 코드 작성

---

k8s/deployment.yaml

- eks argo 배포 과정에 필요한 yaml 추가
- aws과 ecr에 연관된 설정이 포함된 .yaml 파일 작성
-

Edu 286 feat: k8s deployment.yaml 작성

---

build.gradle
src/main/java/com/education/takeit/global/exception/GlobalExceptionHandler.java
src/main/java/com/education/takeit/global/validator/password/PasswordValidator.java
src/main/java/com/education/takeit/global/validator/password/ValidPassword.java
src/main/java/com/education/takeit/user/controller/UserController.java
src/main/java/com/education/takeit/user/dto/ReqSignupDto.java
src/test/java/com/education/takeit/user/ReqSingupDtoTest.java

- 회원가입 검증 로직 추가
- GlobalExceptionHandler 내용 추가
- 테스트 코드 작성

Edu 298 be 회원가입 검증 로직 추가 필요

---

src/main/java/com/education/takeit/feedback/client/InternalClient.java
src/main/java/com/education/takeit/global/dto/StatusCode.java
src/test/java/com/education/takeit/feedback/service/FeedbackServiceTest.java

- 피드백 서비스의 코드를 수정
- 주요 변경 내용은 Jira의 EDU-287, EDU-301을 참고해주세요
- 주요 내용
- FastAPI 측 리팩터링에 따른 연결 URI 수정
- 204 No Content를 처리하는 onStatus 코드, StatusCode 삭제
- Null 검증 코드 삭제
- 리팩터링 내용과 일치하도록 테스트 코드 수정(204 코드 테스트 삭제)

EDU-301 피드백 서비스 수정

---

src/main/resources/application-local.yml

- application-local.yml 파일 작성
- application-local.yml을 통해 로컬 DB로 작업이 용이하도록 함
-

EDU-309 chore: application-local.yml 파일 작성

---

.github/workflows/integration.yml
k8s/deployment.yaml

- GithubActions 워크플로우 수정, Argo Deployment.yaml 수정
- CI과정에서 이미지 태그를 latest와 구분이 되도록 수정
- Argo Deployment.yaml에서 ecr에서 이미지 변동을 감지해서 CD하도록 수정
-

EDU-329 fix: GithubActions 워크플로우 수정, Argo Deployment.yaml 수정

---

src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
src/main/java/com/education/takeit/roadmap/dto/MyPageResDto.java
src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
src/main/java/com/education/takeit/user/repository/UserRepository.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java

EDU-328 feat: 마이페이지 진척도에 닉네임 반환 추가

---

src/test/java/com/education/takeit/user/UserServiceTest.java

EDU-328 fix: UserServiceTest 코드 수정

---

k8s/deployment.yaml

- argo deployment.yaml 불러오는 이미지 태그 수정
- 1.0.0 이미지 태그를 불러오지 않고 latest 태그를 불러오도록 수정
-

EDU-329 fix: argo deployment.yaml 불러오는 이미지 태그 수정

---

k8s/deployment.yaml
src/test/java/com/education/takeit/user/UserServiceTest.java

- argo deployment.yaml 불러오는 이미지 태그 수정
- 1.0.0 태그대신 latest 태그를 불러오도록 수정
-

fix: argo deployment.yaml 불러오는 이미지 태그 수정

---

k8s/deployment.yaml

- argo Deployment.yaml 파일에 환경변수추가
- 실행에 필요한 환경변수
-

EDU-329 fix: argo Deployment.yaml 파일에 환경변수추가

---

k8s/deployment.yaml

- argo Deployment.yaml 파일에 환경변수추가
- 실행에 필요한 환경변수 추가
-

fix: argo Deployment.yaml 파일에 환경변수추가

---

src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
src/main/resources/application.yml
src/test/java/com/education/takeit/roadmap/service/RoadmapCreateTest.java

- 재진단 시 기존 로드맵 삭제 및 새로운 로드맵 저장 기능 추가
- 재진단 시 기존 로드맵 삭제 및 새로운 로드맵 저장 기능 추가
- 포트 번호 9800으로 변경
- 기본 로드맵 저장 시 기본 로드맵을 반환하도록 수정
-

Edu 341 be 재진단 관련 기능 추가

---

src/main/java/com/education/takeit/diagnosis/controller/DiagnosisController.java
src/main/java/com/education/takeit/feedback/controller/FeedbackController.java
src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
src/main/java/com/education/takeit/user/controller/UserController.java

EDU-342 chore: swagger 설명 형식 통일

---

src/main/java/com/education/takeit/TakeitApplication.java

- 클라우드 환경에서 통신 되도록 수정
- 클라우드 환경에서 통신 되도록 수정
-

EDU-286 fix: 클라우드 환경에서 통신 되도록 수정

---

src/main/java/com/education/takeit/global/config/SecurityConfig.java
src/main/java/com/education/takeit/global/config/WebConfig.java

- 클라우드 환경의 백엔드와 프론트 연결
- 클라우드 환경의 백엔드와 프론트 연결
-

EDU-347 fix: 클라우드 환경의 백엔드와 프론트 연결

---

k8s/deployment.yaml

- argo deployment.yaml에 fastapi 변수 추가
- argo deployment.yaml에 fastapi 변수 추가
-

EDU-347 fix: argo deployment.yaml에 fastapi 변수 추가

---

k8s/deployment.yaml

- argo deployment.yaml 오타 수정
- argo deployment.yaml 오타 수정
-

EDU-347 fix: argo deployment.yaml 오타 수정

---

k8s/deployment.yaml

- argo deployment.yaml 오타 수정
- argo deployment.yaml 오타 수정
-

fix: argo deployment.yaml 오타 수정

---

src/main/java/com/education/takeit/diagnosis/controller/DiagnosisController.java
src/main/java/com/education/takeit/exam/controller/ExamController.java
src/main/java/com/education/takeit/feedback/controller/FeedbackController.java
src/main/java/com/education/takeit/oauth/controller/OAuthController.java
src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
src/main/java/com/education/takeit/user/controller/UserController.java

EDU-349 docs: Swagger description 수정

---

k8s/deployment.yaml
src/main/java/com/education/takeit/diagnosis/controller/DiagnosisController.java
src/main/java/com/education/takeit/exam/controller/ExamController.java
src/main/java/com/education/takeit/feedback/controller/FeedbackController.java
src/main/java/com/education/takeit/oauth/controller/OAuthController.java
src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
src/main/java/com/education/takeit/user/controller/UserController.java

docs: Swagger description 수정

---

src/main/java/com/education/takeit/exam/enums/Difficulty.java
src/main/java/com/education/takeit/exam/service/ExamLevelCalculator.java
src/main/java/com/education/takeit/exam/service/ExamService.java
src/main/java/com/education/takeit/global/client/AIClient.java
src/main/java/com/education/takeit/global/dto/StatusCode.java
src/main/java/com/education/takeit/roadmap/entity/Roadmap.java
src/main/java/com/education/takeit/roadmap/repository/RoadmapRepository.java
src/main/resources/db/20250501.sql

- 사후 평가 레벨 재정의 등 이후 로직 구현
- 시잔 평가 이후 로직 구현
- 코드 리팩토링 (계산 관련 메소드 추출하여 새로운 컴포넌트로 작성)

Edu 297 be 사전 사후 fast api 연결

---

k8s/deployment.yaml

- argo deployment.yaml 수정하기
- argo가 새로 업로드된 이미지 태그를 알아보기 쉽도록 image updater가 바라보는 이미지 태그 값을 변경
-

Edu 329 fix: argo deployment.yaml 수정하기

---

src/main/java/com/education/takeit/diagnosis/controller/DiagnosisController.java
src/main/java/com/education/takeit/global/dto/StatusCode.java
src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
src/main/java/com/education/takeit/roadmap/dto/GuestRoadmapSaveReqDto.java
src/main/java/com/education/takeit/roadmap/entity/Roadmap.java
src/main/java/com/education/takeit/roadmap/entity/RoadmapManagement.java
src/main/java/com/education/takeit/roadmap/repository/RoadmapManagementRepository.java
src/main/java/com/education/takeit/roadmap/repository/RoadmapRepository.java
src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
src/main/java/com/education/takeit/roadmap/service/SubjectService.java
src/main/resources/application.yml
src/main/resources/db/20250501.sql

- roadmap, roadmap_management entity 변경
- roadmap entity의 userId를 roadmap_management로 이동
- roadmap 컨트롤러의 API 수정
-

Edu 350 be roadmap entity의 user id를 roadmap management로 이동

---

src/main/java/com/education/takeit/exam/controller/ExamController.java
src/main/java/com/education/takeit/exam/service/ExamService.java

EDU-297 feat: 사전평가 마무리

---

.github/workflows/codeStyleCheck.yml
.github/workflows/integration.yml
.gitignore
docker-compose.yml
k8s/deployment.yaml
src/main/java/com/education/takeit/exam/entity/Exam.java
src/main/java/com/education/takeit/solution/entity/Solution.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

- 평가 문제, 해설 Entity 추가
- 평가 문제, 해설 테이블 생성
- ci에서 적절한 환경 변수를 불러올 수 있도록 workflow 수정
- test빌드 과정에서 ,env.test.properties를 참고 안 하도록 .yml 파일 수정
-

Edu 359 feat: 평가 문제, 해설 Entity 추가

---

docker-compose.yml
src/main/java/com/education/takeit/recommend/controller/RecommendController.java
src/main/java/com/education/takeit/recommend/dto/UserContentResDto.java
src/main/java/com/education/takeit/recommend/entity/TotalContent.java
src/main/java/com/education/takeit/recommend/entity/UserContent.java
src/main/java/com/education/takeit/recommend/repository/UserContentRepository.java
src/main/java/com/education/takeit/recommend/service/RecommendService.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml
src/main/resources/db/20250501.sql

EDU-358 feat: 추천 컨텐츠 조회

---

.github/workflows/codeStyleCheck.yml
.github/workflows/integration.yml
.gitignore
docker-compose.yml
k8s/deployment.yaml
src/main/java/com/education/takeit/diagnosis/controller/DiagnosisController.java
src/main/java/com/education/takeit/exam/controller/ExamController.java
src/main/java/com/education/takeit/exam/entity/Exam.java
src/main/java/com/education/takeit/global/dto/StatusCode.java
src/main/java/com/education/takeit/global/exception/GlobalExceptionHandler.java
src/main/java/com/education/takeit/recommend/controller/RecommendController.java
src/main/java/com/education/takeit/recommend/dto/UserContentResDto.java
src/main/java/com/education/takeit/recommend/entity/TotalContent.java
src/main/java/com/education/takeit/recommend/entity/UserContent.java
src/main/java/com/education/takeit/recommend/repository/UserContentRepository.java
src/main/java/com/education/takeit/recommend/service/RecommendService.java
src/main/java/com/education/takeit/solution/entity/Solution.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml
src/main/resources/db/20250501.sql

- 반환형식 통일
- userDetail null 예외 처리

Refactor/컨트롤러반환형식 변경

---

k8s/deployment.yaml
src/main/java/com/education/takeit/solution/controller/SolutionController.java
src/main/resources/application.yml

- argo deployment.yaml
- argo deployment.yaml 내용 수정
-

Edu 359 fix: argo deployment.yaml

---

k8s/deployment.yaml

- argo deployment.yaml 수정
- argo deployment.yaml 수정
-

EDU-359 fix: argo deployment.yaml

---

src/main/java/com/education/takeit/global/client/AIClient.java
src/main/java/com/education/takeit/oauth/client/GoogleOauthClient.java
src/main/java/com/education/takeit/oauth/client/KakaoOauthClient.java
src/main/java/com/education/takeit/oauth/client/NaverOauthClient.java

EDU-380 feat: 소셜로그인 RestClient 재요청 처리

---

build.gradle

EDU-380 chore: Spring Retry 의존성 추가

---

src/main/java/com/education/takeit/solution/dto/SolutionResDto.java
src/main/java/com/education/takeit/solution/service/SolutionService.java

- 해설 조회 반환값 수정
- 해설 반환값에 회차 정보 추가
-

Edu 410 fix: 해설 조회 반환값 수정

---

src/main/java/com/education/takeit/roadmap/dto/SubjectFindResDto.java
src/main/java/com/education/takeit/roadmap/service/SubjectService.java
src/test/java/com/education/takeit/roadmap/service/SubjectFindTest.java

Edu 426 be 로드맵 과목 조회에서 추천 컨텐츠도 같이 반환하기

---

src/main/java/com/education/takeit/user/controller/UserController.java

- 문법 살짝 수정
- Controller Message 제네릭 타입 문법 살짝 수정
-

EDU-434 fix: 문법 살짝 수정

---

build.gradle
src/main/java/com/education/takeit/chat/controller/ChatController.java
src/main/java/com/education/takeit/chat/dto/ChatReqDto.java
src/main/java/com/education/takeit/chat/dto/ChatResDto.java
src/main/java/com/education/takeit/chat/entity/Chat.java
src/main/java/com/education/takeit/chat/handler/StompHandler.java
src/main/java/com/education/takeit/chat/handler/StompPrincipal.java
src/main/java/com/education/takeit/chat/repository/ChatRepository.java
src/main/java/com/education/takeit/chat/service/ChatService.java
src/main/java/com/education/takeit/global/client/AIClient.java
src/main/java/com/education/takeit/global/config/SecurityConfig.java
src/main/java/com/education/takeit/global/config/WebConfig.java
src/main/java/com/education/takeit/global/config/WebSocketConfig.java
src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
src/main/resources/db/20250501.sql

- 챗봇 통신 기능 개발
- 챗봇 기능을 위한 websocket 통신 기능 개발
-

Edu 411 be 챗봇 기능 개발

---

src/main/java/com/education/takeit/TakeitApplication.java
src/main/java/com/education/takeit/exam/controller/ExamController.java
src/main/java/com/education/takeit/exam/service/ExamService.java
src/main/java/com/education/takeit/recommend/controller/RecommendController.java
src/main/java/com/education/takeit/recommend/service/RecommendService.java
src/main/resources/application.yml

- 사전 평가 후 추천 컨텐츠 요청하는 로직 수정
- FastAPI로 보내는 추천 컨텐츠 생성 요청을 비동기식으로 처리
- 응답 받은 추천 컨텐츠는 별도의 클래스로 분리하여 Transactional 어노테이션 추가
-

Edu 442 fix: 사전 평가 후 추천 컨텐츠 요청하는 로직 수정

---

src/main/java/com/education/takeit/interview/controller/InterviewController.java
src/main/java/com/education/takeit/interview/dto/InterviewContentResDto.java
src/main/java/com/education/takeit/interview/dto/UserInterviewReplyReqDto.java
src/main/java/com/education/takeit/interview/entity/UserInterviewReply.java
src/main/java/com/education/takeit/interview/service/InterviewService.java

- 면접 사용자 응답 엔티티 컬럼 추가
- ai 면접 피드백 DB에 저장 

Edu 446 be 면접 피드백 생성 요청 dto 수정

---

src/main/java/com/education/takeit/interview/controller/InterviewController.java
src/main/java/com/education/takeit/interview/dto/InterviewContentResDto.java
src/main/java/com/education/takeit/interview/dto/UserInterviewReplyReqDto.java
src/main/java/com/education/takeit/interview/repository/UserInterviewReplyRepository.java
src/main/java/com/education/takeit/interview/service/InterviewService.java
src/main/resources/application.yml

- 면접 문제 제공 시 회차 정보 같이 넘기기
- 사용자 면접 응답 받을 때도 회차 정보 같이 받기 

EDU-466 feat: 면접 문제 제공 시 회차 정보 카운팅

---

src/main/java/com/education/takeit/global/client/AIClient.java
src/main/java/com/education/takeit/interview/controller/InterviewController.java
src/main/java/com/education/takeit/interview/dto/InterviewAllReplyReqDto.java
src/main/java/com/education/takeit/interview/dto/InterviewFeedbackResDto.java
src/main/java/com/education/takeit/interview/service/InterviewService.java

- 면접 답변 문제별로 묶어서 한번에 요청 받기 
- openAI에서 피드백 받아오는 걸 fastAPI 서버에 요청 보내는 것으로 수정 

EDU-468 feat: 면접 응답 한번에 받고 fastAI 서버로 피드백 요청 보내기

---

src/main/java/com/education/takeit/user/controller/UserController.java

Edu 471 be 로그아웃 시 쿠키에서 리프레시 토큰 삭제

---

src/main/java/com/education/takeit/global/security/JwtUtils.java
src/main/java/com/education/takeit/interview/controller/InterviewController.java
src/main/java/com/education/takeit/interview/service/InterviewService.java
src/main/java/com/education/takeit/oauth/service/GoogleOAuthService.java
src/main/java/com/education/takeit/oauth/service/KakaoOAuthService.java
src/main/java/com/education/takeit/oauth/service/NaverOAuthService.java
src/main/java/com/education/takeit/user/controller/UserController.java
src/main/java/com/education/takeit/user/dto/UserSigninResDto.java
src/main/java/com/education/takeit/user/entity/User.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java
src/main/resources/application.yml
src/main/resources/db/20250501.sql
src/test/java/com/education/takeit/oauth/service/GoogleOAuthServiceTest.java
src/test/java/com/education/takeit/oauth/service/KakaoOAuthServiceTest.java
src/test/java/com/education/takeit/oauth/service/NaverOAuthServiceTest.java
src/test/java/com/education/takeit/user/UserServiceTest.java

-  로그인시 privacyStatus같이 반환하도록 수정
- 면접 기능 이용시 필요한 사용자의 privacyStatus 값을 로그인할때 반환하도록 수정

EDU-485 fix: 로그인시 privacyStatus같이 반환하도록 수정

---

src/main/java/com/education/takeit/feedback/service/FeedbackService.java
src/main/java/com/education/takeit/global/dto/StatusCode.java
src/main/java/com/education/takeit/recommend/service/RecommendService.java
src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java
src/test/java/com/education/takeit/user/ReqSingupDtoTest.java
src/test/java/com/education/takeit/user/UserServiceTest.java

- 로그아웃 성공 테스트 코드 추가 및 문서화에 맞게 수정
- 단위 테스트 코드 문서화에 맞게 수정
- 로그아웃 성공 테스트 코드 추가
-

Edu 493 test: 로그아웃 성공 테스트 코드 추가 및 문서화에 맞게 수정

---

build.gradle
src/main/java/com/education/takeit/diagnosis/entity/Choice.java
src/main/java/com/education/takeit/diagnosis/entity/Diagnosis.java
src/main/java/com/education/takeit/kafka/recommand/consumer/RecomSuccessKafkaConsumer.java
src/main/resources/application-test.yml
src/test/java/com/education/takeit/TakeitApplicationTests.java

Edu 489 be jacoco sonar qube 적용

---

build.gradle

Revert "EDU-489 fix: jacoco + sonarqube 수정"

---

src/main/java/com/education/takeit/interview/dto/InterviewHistoryResDto.java
src/main/java/com/education/takeit/interview/service/InterviewService.java

Edu 515 be 면접 내역 조회 dto 수정

---

build.gradle
src/main/java/com/education/takeit/kafka/common/config/KafkaConsumerConfig.java

- 카프카 hearbeat session 유지 시간 변경

Edu 524 be 카프카 hearbeat session 유지 시간 변경 spring

---

src/main/java/com/education/takeit/admin/failLog/controller/AdminFailLogController.java
src/main/java/com/education/takeit/admin/failLog/dto/DailyLogCountDto.java
src/main/java/com/education/takeit/admin/failLog/dto/FeedbackFailLogDto.java
src/main/java/com/education/takeit/admin/failLog/dto/RecomFailLogDto.java
src/main/java/com/education/takeit/admin/failLog/spec/FailLogSpecifications.java
src/main/java/com/education/takeit/global/config/WebConfig.java
src/main/java/com/education/takeit/global/dto/StatusCode.java
src/main/java/com/education/takeit/kafka/feedback/entity/FeedbackFailLog.java
src/main/java/com/education/takeit/kafka/feedback/repository/FeedbackFailRepository.java
src/main/java/com/education/takeit/kafka/feedback/service/FeedbackFailLogService.java
src/main/java/com/education/takeit/kafka/recommand/entity/RecomFailLog.java
src/main/java/com/education/takeit/kafka/recommand/repository/RecomFailRepository.java
src/main/java/com/education/takeit/kafka/recommand/service/RecomFailLogService.java
src/main/resources/application.yml
src/main/resources/db/20250614.sql

- 목록 조회(페이징 + 검색)
- 로그 일자별 합계 조회
- 재시도 요청 

Edu 530 be 관리자 피드백 추천 컨텐츠 재생성 요청

---

src/main/java/com/education/takeit/interview/service/InterviewService.java
src/main/java/com/education/takeit/user/controller/UserController.java
src/main/java/com/education/takeit/user/dto/TokenRefreshResDto.java
src/main/java/com/education/takeit/user/service/UserService.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java

- 면접 응답 리스트에 담아서 saveAll()
- 리프레시 토큰 발급해서 반환할 때 privacyStatus 같이 주기 

EDU-539 feat: 면접 응답 저장 메서드 수정 및 리프레시 토큰 반환 시 privacyStatus 반환

---

src/main/java/com/education/takeit/interview/dto/InterviewHistoryResDto.java
src/main/java/com/education/takeit/interview/service/InterviewService.java

Edu 543 be ai 키워드 db에 저장

---

src/main/java/com/education/takeit/user/entity/User.java
src/main/java/com/education/takeit/user/service/UserServiceImpl.java

fix: 회원가입 시 privacyStatus 기본값 추가

---

src/main/resources/application-dev.yml

- 커넥션 풀 100개로 수정
- 커넥션 풀 100개로 수정
-

EDU-546 fix: 커넥션 풀 100개로 수정

---

src/main/resources/application-dev.yml

- gateway timeout 시간 3분으로 수정
- gateway timeout 시간 3분으로 수정
-

EDU-546 fix: gateway timeout 시간 3분으로 수정

---

src/test/java/com/education/takeit/recommend/RecommendServiceTest.java

- 유저/과목 존재하지 않을 경우 추천 컨텐츠 저장 실패 테스트 코드 추가 

Edu 553 be recommend 단위 테스트 수정

---

src/main/java/com/education/takeit/exam/service/ExamService.java
src/test/java/com/education/takeit/exam/service/ExamServiceTest.java

EDU-554 test: exam 단위 테스트 코드 추가
